//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABA1_MM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        static Employee emp;

        public static Employee CreateEmployee(int ID, string Surname, string Name, string Patronymic, int TitleID)
        {
            emp = new Employee();
            emp.ID = ID;
            emp.Surname = Surname;
            emp.Name = Name;
            emp.Pantonymic = Patronymic;
            emp.TitleID = TitleID;
            emp.Telephone = "не задано";
            emp.Email = "не задано";
            return emp;
        }
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Pantonymic { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public int TitleID { get; set; }
    
        public virtual Title Title { get; set; }
    }
}
